name: Playwright Tests

on:
  pull_request:
    types: [opened]
    branches: [main]
    paths-ignore:
      - "README.md"
      - "LICENSE"
      - ".github/"
      - ".husky/"
      - "test-results/"
      - ".vscode/"
      - "scripts/"
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
      - "LICENSE"
      - ".github/"
      - ".husky/"
      - "test-results/"
      - ".vscode/"
      - "scripts/"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

permissions: write-all

jobs:
  test:
    timeout-minutes: 10
    if: ${{!contains(github.event.pull_request.body, '[skip ci]')}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'pnpm'
      - name: Cache playwright binaries
        uses: actions/cache@v2
        id: playwright-cache
        with:
          path: |
            ~/.cache/ms-playwright
          key: cache-playwright-linux
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Install Playwright Browsers
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: pnpm e2e
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
