name: storybook

on:
  push:
    branches:
      - develop
  pull_request:
    types: [closed]
    branches: [develop]
    paths-ignore:
      - "README.md"
      - "LICENSE"
      - ".github/"
      - ".husky/"
      - "test-results/"
      - ".vscode/"
      - "scripts/"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: ${{!contains(github.event.pull_request.body, '[skip ci]')}}
    strategy:
      matrix:
        node-version: [16]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --shamefully-hoist
      - name: Build storybook
        run: pnpm build-storybook
      - uses: actions/upload-pages-artifact@v1
        with:
          path: storybook-static

  deploy:
    timeout-minutes: 5
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
