name: Storybook

on:
  push:
    branches:
      - develop
    paths:
      - 'src/components/**/*.tsx'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: ${{!contains(github.event.pull_request.body, '[skip ci]')}}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-node-and-restore-packages
      - name: Build storybook
        run: pnpm build-storybook
      - uses: actions/upload-pages-artifact@v1
        with:
          path: storybook-static
  
  deploy:
    timeout-minutes: 5
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    outputs:
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
  
  vrt:
    runs-on: ubuntu-latest
    needs: deploy
    timeout-minutes: 10
    permissions:
      contents: read
      id-token: write
      pull-requests: write
    env: 
      REG_SUIT_CLIENT_ID: ${{secret.REG_SUIT_CLIENT_ID}}
      REG_SUIT_GCS_BUCKET_NAME: ${{secret.REG_SUIT_GCS_BUCKET_NAME}}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: ./.github/actions/setup-node-and-restore-packages
      - name: workaround for detached HEAD
        run: |
          git checkout ${GITHUB_REF#refs/heads/} || git checkout -b ${GITHUB_REF#refs/heads/} && git pull
      - id: auth
        uses: google-github-actions/auth@v01
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
      - name: Capture screenshots
        run: pnpm exec storycap ${{ needs.deploy.outputs.url }}
      - name: Run reg-suit
        run: pnpm exec reg-suit run

  set-status: 
    runs-on: ubuntu-latest
    needs: deploy
    steps:
    - uses: actions/checkout@v3
    - name: Set status
      uses: Sibz/github-status-action@v1
      with: 
        authToken: ${{ secrets.GITHUB_TOKEN }}
        context: 'GitHub Pages'
        description: 'Deployment has completed'
        state: 'success'
        sha: ${{ github.event.pull_request.head.sha || github.sha }}
        target_url: ${{ needs.deploy.outputs.url }}

